import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {
  buildHostAutoInitImportId,
  normalizeAstroExposesForFederation,
  normalizeRemotes,
} from '../dist/index.js';

test('normalizes core-style remote value name@url into remote object config', () => {
  const remotes = normalizeRemotes({
    remote: 'remote@http://localhost:4173/mf-manifest.json',
  });

  assert.deepEqual(remotes, {
    remote: {
      type: 'var',
      name: 'remote',
      entry: 'http://localhost:4173/mf-manifest.json',
      entryGlobalName: 'remote',
      shareScope: 'default',
    },
  });
});

test('normalizes plain url remotes using the remote key as global name', () => {
  const remotes = normalizeRemotes({
    remote: 'http://localhost:4173/mf-manifest.json',
  });

  assert.deepEqual(remotes, {
    remote: {
      type: 'var',
      name: 'remote',
      entry: 'http://localhost:4173/mf-manifest.json',
      entryGlobalName: 'remote',
      shareScope: 'default',
    },
  });
});

test('keeps non-url @ strings unchanged', () => {
  const remotes = normalizeRemotes({
    remote: '@scope/remote',
  });

  assert.deepEqual(remotes, {
    remote: '@scope/remote',
  });
});

test('keeps object remotes unchanged', () => {
  const remotes = normalizeRemotes({
    remote: {
      name: 'remote',
      entry: 'http://localhost:4173/mf-manifest.json',
    },
  });

  assert.deepEqual(remotes, {
    remote: {
      name: 'remote',
      entry: 'http://localhost:4173/mf-manifest.json',
    },
  });
});

test('builds deterministic host auto init virtual module id', () => {
  const moduleId = buildHostAutoInitImportId('astro_host');

  assert.equal(
    moduleId,
    '__mf__virtual/astro_host__H_A_I__hostAutoInit__H_A_I__.js',
  );
});

test('auto-wraps .astro exposes into generated TS wrappers', () => {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'mf-astro-exposes-'));

  try {
    fs.mkdirSync(path.join(projectRoot, 'src'), { recursive: true });
    fs.writeFileSync(
      path.join(projectRoot, 'src', 'RemoteCard.astro'),
      '<div>remote card</div>\n',
      'utf8',
    );

    const normalizedExposes = normalizeAstroExposesForFederation(
      {
        './RemoteCard': './src/RemoteCard.astro',
        './widget': './src/widget.ts',
      },
      projectRoot,
    );

    assert.equal(normalizedExposes['./widget'], './src/widget.ts');
    assert.match(
      normalizedExposes['./RemoteCard'],
      /^\.\/\.__mf__temp\/astro-exposes\/.+\.ts$/,
    );

    const wrapperRelativePath = normalizedExposes['./RemoteCard'].replace(/^\.\//, '');
    const wrapperAbsolutePath = path.join(projectRoot, wrapperRelativePath);
    const wrapperContents = fs.readFileSync(wrapperAbsolutePath, 'utf8');

    assert.match(wrapperContents, /Auto-generated by @module-federation\/astro/);
    assert.match(wrapperContents, /@ts-ignore/);
    assert.match(wrapperContents, /RemoteCard\.astro/);
  } finally {
    fs.rmSync(projectRoot, { recursive: true, force: true });
  }
});
