import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { expect, test } from "vitest";

import {
  buildHostAutoInitImportId,
  moduleFederationAstro,
  normalizeAstroExposesForFederation,
  normalizeRemotes,
} from "../src/index";

test("normalizes core-style remote value name@url into remote object config", () => {
  const remotes = normalizeRemotes({
    remote: "remote@http://localhost:4173/mf-manifest.json",
  });

  expect(remotes).toEqual({
    remote: {
      type: "var",
      name: "remote",
      entry: "http://localhost:4173/mf-manifest.json",
      entryGlobalName: "remote",
      shareScope: "default",
    },
  });
});

test("normalizes plain url remotes using the remote key as global name", () => {
  const remotes = normalizeRemotes({
    remote: "http://localhost:4173/mf-manifest.json",
  });

  expect(remotes).toEqual({
    remote: {
      type: "var",
      name: "remote",
      entry: "http://localhost:4173/mf-manifest.json",
      entryGlobalName: "remote",
      shareScope: "default",
    },
  });
});

test("keeps non-url @ strings unchanged", () => {
  const remotes = normalizeRemotes({
    remote: "@scope/remote",
  });

  expect(remotes).toEqual({
    remote: "@scope/remote",
  });
});

test("keeps object remotes unchanged", () => {
  const remotes = normalizeRemotes({
    remote: {
      name: "remote",
      entry: "http://localhost:4173/mf-manifest.json",
    },
  });

  expect(remotes).toEqual({
    remote: {
      name: "remote",
      entry: "http://localhost:4173/mf-manifest.json",
    },
  });
});

test("builds deterministic host auto init virtual module id", () => {
  const moduleId = buildHostAutoInitImportId("astro_host");

  expect(moduleId).toBe("__mf__virtual/astro_host__H_A_I__hostAutoInit__H_A_I__.js");
});

test("auto-wraps .astro exposes into generated TS wrappers", () => {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), "mf-astro-exposes-"));

  try {
    fs.mkdirSync(path.join(projectRoot, "src"), { recursive: true });
    fs.writeFileSync(
      path.join(projectRoot, "src", "RemoteCard.astro"),
      "<div>remote card</div>\n",
      "utf8",
    );

    const normalizedExposes = normalizeAstroExposesForFederation(
      {
        "./RemoteCard": "./src/RemoteCard.astro",
        "./widget": "./src/widget.ts",
      },
      projectRoot,
    );

    expect(normalizedExposes["./widget"]).toBe("./src/widget.ts");
    expect(normalizedExposes["./RemoteCard"]).toMatch(/^\.\/\.__mf__temp\/astro-exposes\/.+\.ts$/);

    const wrapperRelativePath = normalizedExposes["./RemoteCard"];

    expect(typeof wrapperRelativePath).toBe("string");

    if (typeof wrapperRelativePath !== "string") {
      throw new TypeError("Expected wrapped .astro expose to resolve to a string path.");
    }

    const normalizedWrapperRelativePath = wrapperRelativePath.replace(/^\.\//, "");
    const wrapperAbsolutePath = path.join(projectRoot, normalizedWrapperRelativePath);
    const wrapperContents = fs.readFileSync(wrapperAbsolutePath, "utf8");

    expect(wrapperContents).toMatch(/Auto-generated by @module-federation\/astro/);
    expect(wrapperContents).toMatch(/@ts-ignore/);
    expect(wrapperContents).toMatch(/RemoteCard\.astro/);
  } finally {
    fs.rmSync(projectRoot, { recursive: true, force: true });
  }
});

test("injects host auto-init and web target define for remotes in dev", () => {
  const injectedScripts = [];
  const updatedConfigs = [];
  const integration = moduleFederationAstro({
    mode: "client",
    name: "astro_host",
    remotes: {
      astro_remote: "astro_remote@http://localhost:4322/mf-manifest.json",
    },
  });

  const setupArgs = {
    command: "dev",
    injectScript(stage, code) {
      injectedScripts.push({ stage, code });
    },
    updateConfig(config) {
      updatedConfigs.push(config);
      return config as never;
    },
  } as unknown as Parameters<(typeof integration.hooks)["astro:config:setup"]>[0];

  integration.hooks["astro:config:setup"](setupArgs);

  expect(injectedScripts).toHaveLength(1);
  expect(injectedScripts[0].stage).toBe("page");
  expect(injectedScripts[0].code).toMatch(
    /__mf__virtual\/astro_host__H_A_I__hostAutoInit__H_A_I__\.js/,
  );

  expect(updatedConfigs).toHaveLength(1);
  expect(updatedConfigs[0].vite.define.ENV_TARGET).toBe('"web"');
  expect(updatedConfigs[0].vite.optimizeDeps.include).toEqual(["@module-federation/runtime"]);
  expect(updatedConfigs[0].vite.optimizeDeps.exclude[0]).toMatch(/hostAutoInit/);
});

test("does not inject host auto-init when no remotes are configured", () => {
  const injectedScripts = [];
  const updatedConfigs = [];
  const integration = moduleFederationAstro({
    name: "astro_host",
  });

  const setupArgs = {
    command: "dev",
    injectScript(stage, code) {
      injectedScripts.push({ stage, code });
    },
    updateConfig(config) {
      updatedConfigs.push(config);
      return config as never;
    },
  } as unknown as Parameters<(typeof integration.hooks)["astro:config:setup"]>[0];

  integration.hooks["astro:config:setup"](setupArgs);

  expect(injectedScripts).toHaveLength(0);
  expect(updatedConfigs).toHaveLength(1);
  expect(updatedConfigs[0].vite.optimizeDeps.include).toEqual(["@module-federation/runtime"]);
  expect("exclude" in updatedConfigs[0].vite.optimizeDeps).toBe(false);
  expect(updatedConfigs[0].vite.define.ENV_TARGET).toBe("undefined");
});

test("ssr runtime plugin resolves configured local remotes to local source files", async () => {
  const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), "mf-astro-ssr-local-"));
  const hostRoot = path.join(fixtureRoot, "host");
  const remoteRoot = path.join(fixtureRoot, "remote");
  const previousCwd = process.cwd();

  try {
    fs.mkdirSync(path.join(remoteRoot, "src"), { recursive: true });
    fs.mkdirSync(hostRoot, { recursive: true });
    fs.writeFileSync(
      path.join(remoteRoot, "src", "server.ts"),
      'export const getMessage = () => "remote";\n',
      "utf8",
    );

    process.chdir(hostRoot);

    const updatedConfigs = [];
    const integration = moduleFederationAstro({
      name: "astro_host",
      remotes: {
        astro_remote: "astro_remote@http://localhost:4322/mf-manifest.json",
      },
      ssr: {
        localRemotes: {
          astro_remote: "../remote",
        },
      },
    });

    const setupArgs = {
      command: "build",
      injectScript() {},
      updateConfig(config) {
        updatedConfigs.push(config);
        return config as never;
      },
    } as unknown as Parameters<(typeof integration.hooks)["astro:config:setup"]>[0];

    integration.hooks["astro:config:setup"](setupArgs);

    const runtimePlugin = updatedConfigs[0].vite.plugins.find(
      (plugin) => plugin?.name === "@module-federation/astro:ssr-load-remote-runtime",
    );

    expect(runtimePlugin).toBeTruthy();

    const transformed = await runtimePlugin.transform(
      'const mod = await runtime.loadRemote("astro_remote/server");',
      "virtual:__loadRemote__astro_remote_server.js",
      { ssr: true },
    );

    expect(transformed).toBeTruthy();
    expect(transformed.code).toMatch(/import \* as __mf_local_module__/);
    expect(transformed.code).toMatch(/file:\/\//);
    expect(transformed.code).toMatch(/remote\/src\/server\.ts/);
    expect(transformed.code).toMatch(/export \* from/);
  } finally {
    process.chdir(previousCwd);
    fs.rmSync(fixtureRoot, { recursive: true, force: true });
  }
});

test("ssr runtime plugin only injects source fallback in dev", async () => {
  const createPlugin = (command: "dev" | "build") => {
    const updatedConfigs = [];
    const integration = moduleFederationAstro({
      name: "astro_host",
      remotes: {
        astro_remote: "astro_remote@http://localhost:4322/mf-manifest.json",
      },
    });

    const setupArgs = {
      command,
      injectScript() {},
      updateConfig(config) {
        updatedConfigs.push(config);
        return config as never;
      },
    } as unknown as Parameters<(typeof integration.hooks)["astro:config:setup"]>[0];

    integration.hooks["astro:config:setup"](setupArgs);

    return updatedConfigs[0].vite.plugins.find(
      (plugin) => plugin?.name === "@module-federation/astro:ssr-load-remote-runtime",
    );
  };

  const devPlugin = createPlugin("dev");
  const buildPlugin = createPlugin("build");

  expect(devPlugin).toBeTruthy();
  expect(buildPlugin).toBeTruthy();

  const devTransformed = await devPlugin.transform(
    'const mod = await runtime.loadRemote("astro_remote/server");',
    "virtual:__loadRemote__astro_remote_server.js",
    { ssr: true },
  );
  const buildTransformed = await buildPlugin.transform(
    'const mod = await runtime.loadRemote("astro_remote/server");',
    "virtual:__loadRemote__astro_remote_server.js",
    { ssr: true },
  );

  expect(devTransformed.code).toMatch(/loadFromRemoteSource/);
  expect(devTransformed.code).toMatch(/console\.warn/);
  expect(buildTransformed.code).not.toMatch(/loadFromRemoteSource/);
  expect(buildTransformed.code).not.toMatch(/console\.warn/);
});
